version: '3.8'
services:
  db:
    image: postgres:13-alpine
    restart: on-failure
    ports: ["5432:5432"]
    command: ["-c", "wal_level=logical", "-c", "max_wal_senders=5"]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
