version: '3.8'
services:
  zk:
    image: zookeeper:latest
    restart: on-failure
    ports: ["2181:2181"]
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    restart: on-failure
    ports: ["9092:9092"]
    depends_on: ["zk"]
    environment:
      KAFKA_ADVERTISED_LISTENERS: IN://kafka:9094,OUT://host.k3d.internal:9092
      KAFKA_LISTENERS: OUT://:9092,IN://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: IN:PLAINTEXT,OUT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: IN
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
