apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: k3d
servers: 1
agents: 0
registries:
  create:
    name: k3d-registry
    host: "0.0.0.0"
    hostPort: "5000"
  config: |
    mirrors:
      "localhost:5000":
        endpoint:
          - http://k3d-registry:5000
      "host.k3d.internal:5000":
        endpoint:
          - http://k3d-registry:5000
ports:
  - port: 80:80
    nodeFilters: ["loadbalancer"]
    
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik,metrics-server"
        nodeFilters: ["all"]
