name: Artifacts

on: 
  workflow_call:
    secrets:
      GHCR_TOKEN:
        required: true

env:
   REGISTRY: ghcr.io
   HELM_EXPERIMENTAL_OCI: 1
   GHCR_USER: innovationlabsmt
   GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
   GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}

jobs:
  publish_artifact:
    name: Publish release artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: theVersion
        run: echo "::set-output name=theVersion::$(echo ${GITHUB_REF##*/})"
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.GHCR_USER }}
          password: ${{ env.GHCR_TOKEN }}
      - uses: volesen/setup-skaffold@v1.1
        with:
          version: 'v1.28.0'
#       - name: test
#         run: make test
#       - name: publish artifacts
#         run: |
#           helm registry login ${REGISTRY} -u ${{ env.GHCR_USER }} -p ${{ env.GHCR_TOKEN }}
#           ./publish.sh ${{ steps.theVersion.outputs.theVersion }}
#       - name: rm pre-rel
#         run: |
#           REL_ID=$(gh api -X GET repos/{owner}/{repo}/releases --jq '.[] | select(.tag_name == "${{ steps.theVersion.outputs.theVersion }}") | .id')
#           gh api -X PATCH repos/{owner}/{repo}/releases/${REL_ID} -F prerelease=false -F name=${{ steps.theVersion.outputs.theVersion }}
