name: Publish

on: 
  workflow_call:
    secrets:
      GHCR_TOKEN:
        required: true

env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  publish_artifact:
    name: Publish release artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: theVersion
        run: echo "::set-output name=theVersion::$(echo ${GITHUB_REF##*/})"
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: innovationlabsmt
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: volesen/setup-skaffold@v1.1
        with:
          version: 'v1.28.0'
      - run: make test
      - run: |
          helm registry login ghcr.io -u innovationlabsmt -p ${{ secrets.GHCR_TOKEN }}
          ./publish.sh ${{ steps.theVersion.outputs.theVersion }}
      - run: |
          REL_ID=$(gh api -X GET repos/{owner}/{repo}/releases --jq '.[] | select(.tag_name == "${{ steps.theVersion.outputs.theVersion }}") | .id')
          gh api -X PATCH repos/{owner}/{repo}/releases/${REL_ID} -F prerelease=false -F name=${{ steps.theVersion.outputs.theVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
