on: 
  workflow_call:
    secrets:
      GHCR_TOKEN:
        required: true

env:
  GHCR_USER: innovationlabsmt
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

jobs:
  pr:
    name: Build pull request
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'GiGInnovationLabs/endeavour-dotnet-template' }}
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Checkout microservice repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GHCR_TOKEN }}
      - name: Ensure synchronized with dotnet template
        run: |
          make synctpl
          if [ -n "$(git status --porcelain)" ]; then
            git diff HEAD
            echo "::error title=synctpl::Microservice is not up to date with endeavour-dotnet-template, use make synctpl to fix."
            exit 1
          fi
      - name: Test
        run: |
          make test
      - uses: azure/setup-helm@v1
        with:
          version: '3.8.0'
      - uses: volesen/setup-skaffold@v1.1
        with:
          version: 'v1.33.0'
      - name: Checkout util-workflows repository to access common resources
        uses: actions/checkout@v2
        with:
          path: ./util-workflows
          token: ${{ secrets.GHCR_TOKEN }}
          repository: GiGInnovationLabs/util-workflows
      - name: Start Kubernetes cluster
        uses: AbsaOSS/k3d-action@v2.0.0
        with:
          cluster-name: "k3d"
          use-default-registry: false
          args: >-
            --config ./util-workflows/k3d/k3d.yaml
      - name: Create local Docker Registry
        run: |
          k3d registry create localhost --port 5000
          docker network connect k3d-k3d k3d-localhost
          skaffold config set -g default-repo localhost:5000
      - name: Test, build and publish Docker Image of the microservice
        run: |
          sudo echo "127.0.0.1       host.k3d.internal" | sudo tee -a /etc/hosts
          make build
      - name: Start external services
        run: |
          docker-compose -f ./util-workflows/docker-compose/docker-compose.kafka.yaml -f ./util-workflows/docker-compose/docker-compose.postgres.yaml up -d
      - name: Update Helm chart dependencies
        run: |
          helm registry login ghcr.io -u ${{ env.GHCR_USER }} -p ${{ env.GHCR_TOKEN }}
          helm dep up
      - name: Run database migrations
        run: |
          docker login ghcr.io -u ${{ env.GHCR_USER }} -p ${{ env.GHCR_TOKEN }}
          make pgsql
      - name: Checkout devops repository to access Helmfile manifests
        uses: actions/checkout@v2
        with:
          path: ./devops
          token: ${{ secrets.GHCR_TOKEN }}
          repository: GiGInnovationLabs/devops
      - name: Set up Helmfile
        uses: mamezou-tech/setup-helmfile@v0.9.0
        with:
          helmfile-version: "v0.143.0"
          install-kubectl: no
          install-helm: no
      - name: Deploy common resources using Helmfile
        run: |
          helmfile -f ./devops/helmfile/helmfile.yaml -e k3d -l namespace=default sync
      - name: Deploy microservice on k3d and run
        run: |
          make start
