on: 
  workflow_call:
    secrets:
      GHCR_TOKEN:
        required: true

env:
  GHCR_USER: innovationlabsmt
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  REPO_DEVOPS_BRANCH: main
  REPO_WORKFLOWS_BRANCH: main

jobs:
  pr:
    name: Build pull request
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'GiGInnovationLabs/endeavour-dotnet-template' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GHCR_TOKEN }}
      - uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.yml
          token: ${{ secrets.GHCR_TOKEN }}
      - name: Ensure sync with upstream
        run: |
          make synctpl
          if [ -n "$(git status --porcelain | grep -v 'pr.yaml')" ]; then
            git diff HEAD
            echo "::error title=synctpl::Microservice is not up to date with endeavour-dotnet-template, use make synctpl to fix."
            exit 1
          fi

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - uses: mstachniuk/ci-skip@v1
        id: skipTest
        with:
          commit-filter: '[skip test]'
      - name: Test
        if: ${{ steps.skipTest.outputs.ci-skip == 'false' }}
        run: |
          make test

      - uses: actions/checkout@v2
        with:
          path: ./util-workflows
          token: ${{ secrets.GHCR_TOKEN }}
          repository: GiGInnovationLabs/util-workflows
          ref: ${{ env.REPO_WORKFLOWS_BRANCH }}
      - name: Deploy external services
        run: |
          docker-compose up -d
        working-directory: ./util-workflows/k3d

      - uses: volesen/setup-skaffold@v1.1
        with:
          version: 'v1.33.0'
      - uses: rinx/setup-k3d@v0.0.4
        with:
          skipClusterCreation: true
      - name: Start k3d cluster
        working-directory: ./util-workflows/k3d
        run: |
          k3d cluster create --config k3d.yaml
          skaffold config set default-repo localhost:5000

      - uses: actions/checkout@v2
        with:
          path: ./devops
          token: ${{ secrets.GHCR_TOKEN }}
          repository: GiGInnovationLabs/devops
          ref: ${{ env.REPO_DEVOPS_BRANCH }}
      - uses: azure/setup-helm@v1
        with:
          version: '3.8.0'
      - uses: mamezou-tech/setup-helmfile@v0.9.0
        with:
          helmfile-version: "v0.143.0"
          install-kubectl: no
          install-helm: no
      - name: Deploy in-cluster services
        working-directory: ./devops/helmfile
        run: |
          helm registry login ghcr.io -u ${{ env.GHCR_USER }} -p ${{ env.GHCR_TOKEN }}

          helmfile -e k3d deps
          rm -f helmfile.lock

          helmfile -f helmfile.yaml -e k3d -l name=default-support -l name=apcrg sync --skip-deps
      # TODO only run it conditionally for DWH, related to https://github.com/GiGInnovationLabs/endeavour-dwh/issues/53 
      # - name: Deploy KSQLDB / Kafka Connect
      #   working-directory: ./devops/helmfile
      #   run: |
      #     helmfile -f helmfile.yaml -e k3d -l name=strimzi-operator sync --skip-deps
      #     helmfile -f helmfile.yaml -e k3d -l name=strimzi-support -l name=ksqldb sync --skip-deps
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Prepare kafka
        run: |
          for AVRO in `find src/ -name '*.avsc' | grep -v bin`; do
            TOPIC=$(basename $AVRO | sed 's/\.avsc$//g')

            docker run -e BROKERS=host.k3d.internal:9092 --add-host=host.k3d.internal:host-gateway \
              deviceinsight/kafkactl:latest create topic $TOPIC || true

            kubectl exec deploy/apcrg-apicurio-registry -n apicurio -- \
              curl -Ss -XPOST -H "Content-Type:application/json" \
                -d '{"schema":"{\"type\":\"record\",\"name\":\"'${TOPIC}'\",\"fields\":[]}","schemaType":"AVRO"}' \
                localhost:8080/apis/ccompat/v6/subjects/${TOPIC}-value/versions
          done

      - name: Deploy microservice
        run: |
          make pgsql start

      - name: Failure Pod Logging
        if: ${{ failure() }}
        run: |
          for namespace in $(kubectl get namespaces --no-headers -o custom-columns=":metadata.name")
          do
            echo "Namespace: ${namespace} Logs:"
            kubectl logs -l cicd-pod-logging=enabled -n "${namespace}" --tail=1000
            echo "------------------------------------------------------------------------------------------------------------------"
            echo ""
          done