on: 
  workflow_call:
    secrets:
      GHCR_TOKEN:
        required: true

env:
  GHCR_USER: innovationlabsmt
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  REPO_DEVOPS_BRANCH: main
  REPO_WORKFLOWS_BRANCH: main

jobs:
  pr:
    name: Build pull request
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'GiGInnovationLabs/endeavour-dotnet-template' }}
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GHCR_TOKEN }}

      - uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .commitlintrc.yml
          token: ${{ secrets.GHCR_TOKEN }}
      - name: Ensure sync with upstream
        run: |
          make synctpl
          if [ -n "$(git status --porcelain | grep -v 'pr.yaml')" ]; then
            git diff HEAD
            echo "::error title=synctpl::Microservice is not up to date with endeavour-dotnet-template, use make synctpl to fix."
            exit 1
          fi

      - name: Test
        run: |
          make test

      - uses: actions/checkout@v2
        with:
          path: ./util-workflows
          token: ${{ secrets.GHCR_TOKEN }}
          repository: GiGInnovationLabs/util-workflows
          ref: ${{ env.REPO_WORKFLOWS_BRANCH }}
      - name: Deploy external services
        run: |
          docker-compose up -d
        working-directory: ./util-workflows/k3d

      - uses: volesen/setup-skaffold@v1.1
        with:
          version: 'v1.33.0'
      - uses: rinx/setup-k3d@v0.0.4
        with:
          skipClusterCreation: true
      - name: Start k3d cluster
        working-directory: ./util-workflows/k3d
        run: |
          k3d cluster create --config k3d.yaml
          skaffold config set default-repo localhost:5000

      - uses: actions/checkout@v2
        with:
          path: ./devops
          token: ${{ secrets.GHCR_TOKEN }}
          repository: GiGInnovationLabs/devops
          ref: ${{ env.REPO_DEVOPS_BRANCH }}
      - uses: azure/setup-helm@v1
        with:
          version: '3.8.0'
      - uses: mamezou-tech/setup-helmfile@v0.9.0
        with:
          helmfile-version: "v0.143.0"
          install-kubectl: no
          install-helm: no
      - name: Deploy in-cluster services
        run: |
          helmfile -f ./devops/helmfile/helmfile.yaml -e k3d -l namespace=default -l namespace=apicurio sync

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Deploy microservice
        run: |
          helm dep up
          make pgsql kafka start
