on: 
  workflow_call:
    secrets:
      GHCR_TOKEN:
        required: true

jobs:
  create_tag:
    name: Create release tag
    runs-on: ubuntu-latest
    if: ${{ github.run_number > 1 && !contains(github.repository, 'template') }}
    steps:
      - run: |
          dotnet --version
          dotnet --list-sdks
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GHCR_TOKEN }}
      - uses: bahmutov/npm-install@v1.7.7
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}

